### ISSUE TITLE
Is there a way to ignore a path/route?

### ISSUE THREAD

**Issue by forbi** [felixheck/laabr#10]
Im using laabr ^2 with hapi ^16. I would like to ignore some paths/routes from loggin. Is there a way?

**Comment by felixheck** [comment]
Hey @forbi, thanks for your message.

There a undocumented option in `hapi-pino` called `ignorePaths`: https://github.com/pinojs/hapi-pino/pull/30/files

I know it's just available since v3.2.0 and needs hapi v17, but I'd like to separate responsibilities – so feel free to fire a PR to `hapi-pino` with such option in `v2.x.x` :)
