### ISSUE TITLE
Adding pre from request object

### ISSUE THREAD

**Issue by JSteunou** [felixheck/laabr#18]
Hapijs has this feature called preHandler that allows us to add some handler before router handlers (like middlewares as plugin from express) but data from this preHandler are not in `req` object in laabr context.

Could it be possible to add it so it can be used inside `preFormatter` or tokens definition?

**Comment by felixheck** [comment]
Hi @JSteunou — thanks for opening this issue, really appreciating it 👍 

That's true, `req.pre` is not included in laabr's `req` object and that's simply because it's not in hapi-pino's `req` object. So let me create a PR for [hapi-pino](https://github.com/pinojs/hapi-pino). After it's merged, I'll release a minor update where you get access to `pre` within the [`request`/`response` templates](https://github.com/felixheck/laabr/blob/master/docs/tokens-formats-presets.md), like

`{ awesomePreHandler: pre[key] }`

Does this work for you?
Thanks a lot for your feedback.

**Comment by felixheck** [comment]
But TBH: I'm not sure if it will be merged since it's a massive workaround on hapi-pino side

**Comment by JSteunou** [comment]
Yep I did dig a little and found out it was directly related to pino & hapi-pino serializer :( 

I worked around it by adding another preHandler at the end of all my preHandlers that does nothing more than `request.log` and using some `:message[field=msg]` but I am not very proud of it because it adds a specific line of log instead of adding more data into request / response log.

**Comment by felixheck** [comment]
Related: https://github.com/pinojs/hapi-pino/issues/73

**Comment by felixheck** [comment]
Hmm..I'm currently struggling with explaining a good use case.
I mean the responses of such prehandlers are like a payload and you wouldn't expect to print the payload automatically, right?

I would use a `request.log(['info', 'pre'], somestuff)` tbh.
Can you explain your use case in detail?

**Comment by JSteunou** [comment]
For example loading user / profile info in a preHandler, making `request.pre.profile` available for every handlers, and logging `profile.id` for some request / endpoint to help debug / trace.
